CREATE TABLE "XXDOM"."TBL_MANPOWER" 
   (	"ID" NUMBER, 
	"JOB_ORDER_ID" VARCHAR2(20 BYTE), 
	"MANPOWER_ID" NUMBER, 
	"REMARKS" VARCHAR2(255 BYTE), 
	"CREATED_AT" DATE
   );
   
   CREATE UNIQUE INDEX "XXDOM"."TBL_MANPOWER_PK" ON "XXDOM"."TBL_MANPOWER" ("ID");
   
   CREATE SEQUENCE  "XXDOM"."TBL_MANPOWER_PK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
   
   CREATE OR REPLACE TRIGGER "XXDOM"."MANPOWER_AUTO_INC" 
   before insert on "TBL_MANPOWER" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select TBL_MANPOWER_PK_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "XXDOM"."MANPOWER_AUTO_INC" ENABLE;

ALTER TABLE "XXDOM"."TBL_MANPOWER" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "XXDOM"."TBL_MANPOWER" ADD CONSTRAINT "TBL_MANPOWER_PK" PRIMARY KEY ("ID");

GRANT ALL ON TBL_MANPOWER_PK_SEQ TO APPS;
GRANT ALL ON TBL_MANPOWER TO APPS;

SET DEFINE OFF;
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (2,'9',1,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (3,'9',2,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (6,'11',1,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (7,'11',2,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (9,'17',1,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (10,'17',41,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (13,'10',1,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (14,'10',41,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (17,'18',1,null,null);
Insert into TBL_MANPOWER (ID,JOB_ORDER_ID,MANPOWER_ID,REMARKS,CREATED_AT) values (141,'20',41,null,null);
